main_dir          : /global/ml4hep/spss/ftoralesacosta/h1_asymmetry
model_dir         : /global/ml4hep/spss/ftoralesacosta/h1_models
mc                : Rapgap
run_type          : nominal
identifier        : SingleWorker_Q2_Cut
n_iterations      : 10
n_passes          : 5

q_bins            : [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  8., 10.]
